### ISSUE TITLE
[Bug] Pages wont appear after changing targets

### ISSUE THREAD

**Issue by fluid-developer** [KieronQuinn/Smartspacer#45] opened 2023-11-07 16:40 UTC
### Description

When trying to change targets (like, it was Greeting, Date, and now i want it to be Date, Greeting) the navigation buttons are disappearing, the page indicator goes away too. Heres the video (sadly its on g.drive): https://drive.google.com/file/d/1ALZ26eTfCX3ycQA5VVabQLLxWM0TBZub/view?usp=drive_link , using latest smartspacer.

**Comment by KieronQuinn** [comment] 2023-11-16 02:34
I requested access to the video a week or so ago and have not been given access. Please grant it, or I will have to close this as I cannot see what is happening.

**Comment by fluid-developer** [comment] 2023-11-24 15:34
oh, im sorry i didnt expected this to happen, you can try again, here is updated link: https://drive.google.com/file/d/1ALZ26eTfCX3ycQA5VVabQLLxWM0TBZub/view?usp=sharing , i also accepted your request and sorry for late answer, i am busy

**Comment by KieronQuinn** [comment] 2023-12-02 22:37
The Date Target only appears if there's Complications below it. As your video shows, there's only two Complications, so it's hidden when behind the Greeting Target. This is working as intended.

**Closed by KieronQuinn** 2023-12-02 22:37 UTC
Labels: bug
