### ISSUE TITLE
[Bug] Calendar target showing one complication

### ISSUE THREAD

**Issue by sammukhgupta** [KieronQuinn/Smartspacer#71] opened 2023-12-05 16:29 UTC
### Description

When the calendar target shows an event with duration, it also additionally shows one complication. Can the calendar show only event without any other data?

**Comment by KieronQuinn** [comment] 2023-12-05 17:20
No, this is out of scope for the regular Calendar Target. A plugin could do this, but that level of customisation is not something I'll be adding to the built in one.

This is also not a bug, it's a feature request. Please don't label requests as bugs.

**Closed by KieronQuinn** 2023-12-05 17:20 UTC
Labels: bug
