### ISSUE TITLE
[Bug] Tasks from Google Tasks in native At a Glance Smartspace target do nothing when tapped, and don't update after tasks have been completed.

### ISSUE THREAD

**Issue by victor-marino** [KieronQuinn/Smartspacer#180] opened 2024-04-05 07:47 UTC
### Description

I've enabled the At a Glance Smartpace target (not the widget) in the Extended Smartspace (with Native Smartspace turned on).

I can now see pending tasks from Google Tasks in the Extended Smartspace, however their functionality seems to be rather limited/buggy:
* If I tap on any of the tasks, nothing happens. I would expect Google Tasks to open.
* If I check any of those tasks off as completed in Google Tasks, they don't seem to go away in the Extended Smartspace target. I've waited for half an hour or so, but they stay there as if they were still pending.
* If I "dismiss" them in the target itself, they're not market as done in Google Tasks either. Maybe this part is expected, but combined with the two points above it makes for a very confusing experience.

Can any of this be improved? Or are we "handcuffed" here by the way At a Glance itself works?

**Comment by KieronQuinn** [comment] 2024-04-06 20:47
> If I tap on any of the tasks, nothing happens. I would expect Google Tasks to open.

Fixed in 1.7

> If I check any of those tasks off as completed in Google Tasks, they don't seem to go away in the Extended Smartspace target. I've waited for half an hour or so, but they stay there as if they were still pending.

I can't reproduce this, when I mark them as completed they disappear from Smartspacer too. It's likely Native Smartspace has become disconnected during your test which would cause this. Disabling & re-enabling Native Smartspace will fix it.

> If I "dismiss" them in the target itself, they're not market as done in Google Tasks either. Maybe this part is expected, but combined with the two points above it makes for a very confusing experience.

This is the expected behaviour and is also the case in regular At a Glance. Dismissing doesn't make any difference to the tasks in Google Tasks and is beyond my control.

**Closed by KieronQuinn** 2024-04-06 20:47 UTC
Labels: bug
