### ISSUE TITLE
[Other] Empty target without complications is shown

### ISSUE THREAD

**Issue by Rausreisser** [KieronQuinn/Smartspacer#151] opened 2024-02-01 12:46 UTC
### Issue

I have two empty targets behind each other and configured as 'should not be shown without complications'. But the empty target without complications will be displayed. What am I doing wrong? Or a mistake?
(sorry 🙏, my English is not good 😬) 
![Screenshot_2024-02-01-10-18-12-128_com mi android globallauncher](https://github.com/KieronQuinn/Smartspacer/assets/132520478/be1b18b7-a3bc-4bce-904f-6170a85c4ef6)
![Screenshot_2024-02-01-10-19-20-054_com kieronquinn app smartspacer](https://github.com/KieronQuinn/Smartspacer/assets/132520478/e9d88c2f-9cba-4899-92ed-acf7fb27e75c)
![Screenshot_2024-02-01-10-19-47-601_com kieronquinn app smartspacer](https://github.com/KieronQuinn/Smartspacer/assets/132520478/6500ce77-3994-482c-94e1-853c00bc1b6b)
![Screenshot_2024-02-01-10-20-37-913_com kieronquinn app smartspacer](https://github.com/KieronQuinn/Smartspacer/assets/132520478/82a29ef0-50fe-40a7-ab2b-e54ae5a9b6c1)

**Comment by KieronQuinn** [comment] 2024-02-01 20:33
I can't reproduce this. Are there definitely no Complications that are showing in that Target, such as the Blank Complication?

**Comment by Rausreisser** [comment] 2024-02-01 21:20
How can I close this issue?

**Comment by KieronQuinn** [comment] 2024-02-01 21:44
I can close it, don't worry :)

**Closed by KieronQuinn** 2024-02-01 21:44 UTC
