### ISSUE TITLE
[Bug] At a glance is not working properly.

### ISSUE THREAD

**Issue by atuy1219** [KieronQuinn/Smartspacer#240] opened 2024-08-20 13:56 UTC
### Description

Issue:
Tapping on the weather icon has no effect or causes unexpected behavior.

Expected Behavior:
The Google app or Pixel Weather app should open. (Personally, I prefer Pixel Weather to open, so ideally, the Google app would only open on devices without Pixel Weather installed.)

https://github.com/user-attachments/assets/fac3eedb-cd18-4708-9910-7f2dc4d3b3c3

**Comment by KieronQuinn** [comment] 2024-08-20 22:18
I can't reproduce this. Please post a log & screenshots of your Target & Complication setups.

**Comment by atuy1219** [comment] 2024-08-20 23:56
[smartspacer_target_dump_2024-08-21T08_52_56.641798.txt](https://github.com/user-attachments/files/16683629/smartspacer_target_dump_2024-08-21T08_52_56.641798.txt)

![Screenshot_20240821-085327](https://github.com/user-attachments/assets/bb936008-9397-4efc-ac66-f9b0000080a6)
![Screenshot_20240821-085332](https://github.com/user-attachments/assets/c0d9bfe1-a9e6-4685-831e-23f293432227)
![Screenshot_20240821-085405](https://github.com/user-attachments/assets/987297ba-4e85-4f10-9510-6aa5159af530)
![Screenshot_20240821-085408](https://github.com/user-attachments/assets/bc704f08-e529-44c4-803b-93861d8c40a2)
![Screenshot_20240821-085412](https://github.com/user-attachments/assets/ca966cc1-5bf6-4e04-b21c-83713cc2c159)

**Comment by KieronQuinn** [comment] 2024-08-21 00:20
By log I meant a system log, you can install an app like [LogFox](https://github.com/F0x1d/LogFox), start it recording, try tapping the complication where it does nothing, stopping it recording and sending the file it creates.

**Comment by atuy1219** [comment] 2024-08-21 00:32
Oh, I made a mistake. Is this correct this time?

[21_08-09-26-26_902.log](https://github.com/user-attachments/files/16683808/21_08-09-26-26_902.log)

**Comment by KieronQuinn** [comment] 2024-08-21 01:00
That's the correct log, but unfortunately it doesn't tell us anything useful other than it's not being caused by Google changing something. You can confirm this if you're comfortable with ADB shell or a terminal by running:

`am start -a com.google.android.googlequicksearchbox/com.google.android.apps.search.weather.WeatherExportedActivity`

It should open the weather page. As for opening the Pixel Weather app instead, it's something I'll add to the next version. Google haven't done it themselves either yet. Hopefully the change will fix your issue too.

**Comment by atuy1219** [comment] 2024-08-21 02:07
Shouldn't it be "-n" instead of "-a"?

When I run the command with "-a", I get the following error:

Error: Activity not started, unable to resolve Intent { act=com.google.googleandroid.googlequicksearchbox/com.google.android.apps.search.weather.WeatherExportedActivity flg=0x10000000 }

If I replace it with "-n", the command works fine.

I'm also hoping this issue will be fixed in the next update.

Thank you.

**Comment by KieronQuinn** [comment] 2024-08-21 02:14
> Shouldn't it be "-n" instead of "-a"?
> 
> When I run the command with "-a", I get the following error:
> 
> Error: Activity not started, unable to resolve Intent { act=com.google.googleandroid.googlequicksearchbox/com.google.android.apps.search.weather.WeatherExportedActivity flg=0x10000000 }
> 
> If I replace it with "-n", the command works fine.
> 
> I'm also hoping this issue will be fixed in the next update.
> 
> Thank you.

You're right, it should be -n, that's what I get for typing it out and not copy/pasting! Very odd that it fails to launch from Smartspacer if it exists 🤔

**Comment by atuy1219** [comment] 2024-08-21 04:25
https://github.com/user-attachments/assets/50d2d1ed-eb59-4b3e-9d79-598b79d2d855

Upon adding Google Weather to the complication, I have confirmed that it is now operational. However, I am still experiencing issues with the "at a glance" functionality.
[21_08-13-12-09_342.log](https://github.com/user-attachments/files/16685971/21_08-13-12-09_342.log)

**Comment by KieronQuinn** [comment] 2024-08-21 04:36
Currently there are no differences between the At a Glance complication and the Google Weather one, unless you live in an area where you get pushed air quality warnings that are normally displayed in At a Glance, so you may not be missing anything

**Comment by KieronQuinn** [comment] 2024-08-26 22:24
Turns out I eventually got this issue too, it's caused by At a Glance _already_ trying to use Pixel Weather. What triggered it for me was updating to Android 15 QPR1, so I'm not sure how you got the issue early but it's fixed in the next version now (and opens Pixel Weather as it should)

**Comment by atuy1219** [comment] 2024-08-26 23:34
Thank you!

**Comment by KieronQuinn** [comment] 2024-08-27 23:11
Fixed in 1.8

**Closed by KieronQuinn** 2024-08-27 23:11 UTC
Labels: bug
