### ISSUE TITLE
[Bug] High RAM Usage, Possibly by Smartspacer

### ISSUE THREAD

**Issue by DhyanM025** [KieronQuinn/Smartspacer#272] opened 2024-12-13 06:37 UTC
### Description

After the December Pixel updates, there is often heavy RAM usage of up to 98%. Soon after, Smartspacer gets disconnected from native smartspace and RAM usage drops to ~70%. This cycle repeats every few hours.
As I'm unsure whether this can be fixed through a Smartspacer update or a System update, I have posted this in Pixel Help forums as well.

Ps. I'm using a Pixel 6a running Android 15

**Comment by eliasacab** [comment] 2024-12-16 19:42
I had this exact same issue on my Pixel 8 too while on QPR1 (the beta before stable). Rebooting would fix it temporarily. Pretty sure it's an Android issue as updating to the QPR2 beta fixed it for me. Also in Dev settings you can see that it's the system that is hogging all the RAM. Now RAM usage is back to normal for me and apps stay open in the background, including Smartspacer.

Here's my [bug report](https://issuetracker.google.com/issues/376252388):

**Comment by FurhadTheNerd** [comment] 2024-12-17 09:43
hi, when running TOP as root in termux do you see "system service" or whatever it's called hog all the ram? i forgot what it's called I'll report back once it happens again, rebooting temporarily fixes it in my case
i have a pixel 6 oriole running  android 15 on the 2024 December security patch (AP4A.241205.013)
and is rooted with magisk 28.1

**Comment by DhyanM025** [comment] 2024-12-17 11:07
> hi, when running TOP as root in termux do you see "system service" or whatever it's called hog all the ram? i forgot what it's called I'll report back once it happens again, rebooting temporarily fixes it in my case i have a pixel 6 oriole running android 15 on the 2024 December security patch (AP4A.241205.013) and is rooted with magisk 28.1

I am not rooted but running Shizuku. I have checked memory profiling in Android settings and both avg & max usage for OS stays around 2-2.3 GB. Hope this helps.

**Comment by KieronQuinn** [comment] 2024-12-17 11:28
You can run top without root using rish for Shizuku: https://github.com/RikkaApps/Shizuku-API/blob/master/rish/README.md

**Comment by FurhadTheNerd** [comment] 2024-12-18 16:08
UPDATE it happened and i got some logs and screenshots, i think the uptime was around 45 hours, and i only noticed the system hogging memory after i finished recoding a video, and i don't think its related but it could be
behavior before reboot
![Screenshot_20241218-174114](https://github.com/user-attachments/assets/0fd73137-65b8-45cf-8747-ee6291ae8860)
![Screenshot_20241218-174110](https://github.com/user-attachments/assets/5c77ff24-f50e-4e6a-8e06-92931da92b18)
logs during the issue
logcat: 
[sys high mem before reboot.log](https://github.com/user-attachments/files/18185700/sys.high.mem.before.reboot.log)
smart spacer config: 
[smartspacer_target_dump_2024-12-18T17_42_21.977126.txt](https://github.com/user-attachments/files/18185706/smartspacer_target_dump_2024-12-18T17_42_21.977126.txt)
behavior after reboot
![Screenshot_20241218-175050](https://github.com/user-attachments/assets/2944e461-9dc9-41e8-a0d6-9aa3c4769bdf)
![Screenshot_20241218-175122](https://github.com/user-attachments/assets/458e87ef-28b9-4d36-839b-e1b08a348365)
additional information:
magisk 28.1
Zygisk LSPosed v1.10.1 (7115) by Jing Matrix
modules in magisk: 
BCR call recording
pixel expert 
Play Integrity Fix v18.1 by chiteroman
zygisk-detach
Zygisk Assistant
lsposed modules: 
Wa Enhancer
Smartspacer
Pixel Xpert
NoQSlnLockScreen (P4 Mod)
Classic Power Menu

**Comment by FurhadTheNerd** [comment] 2024-12-19 20:12
hello, it happened again after 29 hours of uptime and this time i remembered to get the dumpsys dump, if it does indeed help to pinpoint the cause of the system_server memory leak I'm more than happy to send it to the main developer of smart spacer, it contains some package names and probably identifying information that i do not trust having publicly

**Comment by KieronQuinn** [comment] 2024-12-19 23:46
I'm not sure this issue is being caused by Smartspacer from your earlier screenshots. A leak in system_server shouldn't be related to Smartspacer since it doesn't actually run anything as system - a leak in At a Glance was present during the development stages (before release) and caused a spike in SystemUI, eventually leading to the device crashing, but it never caused a system_server leak so I don't think it's Smartspacer.

Toggling native Smartspace also kills Android System Intelligence, which does run a bunch of system services, so I suspect that's the true cause of your leak here. It would also explain why an update fixes it for some people, since there's usually an ASI update released around or as part of a system update. Perhaps the leak has been fixed and is rolling out slowly.

I'm going to close this, but if anyone finds evidence of Smartspacer actually using more than a normal amount of RAM as is shown above (normal is up to around 300MB or possibly a bit more, depending on the amount of Targets, Complications and clients) I'll reopen.

**Closed by KieronQuinn** 2024-12-19 23:46 UTC
Labels: bug

**Comment by pirasalbe** [comment] 2025-02-05 17:45
As we discussed this on discord, I want to add details to the issue as well.

## Steps to replicate
1. Enable `Enhanced Mode`
2. Enable `Native Smartspace`
3. Wait for a few hours, usually less than 24 in my case
4. The phone will start lagging, failing to keep more than 1 application open at a time.

## How do I make my phone usable again
As mentioned by @DhyanM025:
> Soon after, Smartspacer gets disconnected from native smartspace and RAM usage drops to ~70%. This cycle repeats every few hours.

I typically kill Smartspacer from App Info, but I don't “Reconnect the service”, unlike @KieronQuinn suggested.

These are the steps I do:
1. Steps to replicate the issue
2. Kill Smartspace from App Info
3. **Don't reconnect the service**/disable `Enhanced Mode`. This doesn't restart the SystemUI!

As soon as I do step 2, my phone becomes usable right away. Since reconnecting the service ends up to the issue again, I don't do it, and if I do, it's usually after a few days/weeks.

This is why I believe that the issue is connected with Smartspacer. However, I'm not sure how to gather more evidence.
