### ISSUE TITLE
[Bug] Plugins: Installed tab should only display installed plugins

### ISSUE THREAD

**Issue by yochananmarqos** [KieronQuinn/Smartspacer#3] opened 2023-10-24 21:58 UTC
### Description

Before installing any plugins, the Installed and Available results are identical. I installed the Aftership and Amazon plugin. They do only appear on the Installed section now, however all the rest of the plugins still appear in the Installed section.

Smartspaces 1.1
Pixel 8
Android 14

**Comment by KieronQuinn** [comment] 2023-10-24 22:23
This is intentional, the "Available" tab lists all remaining plugins which are not installed, the "Installed" tab is just those you have installed. You get the same functionality in terms of being shown which have updates on either tab.

**Comment by yochananmarqos** [comment] 2023-10-24 22:26
I think you may be misunderstanding. I don't know how I can be more clear with words, so I'll show you:

![Screenshot_20231024-162421](https://github.com/KieronQuinn/Smartspacer/assets/5437803/fae2f8cd-38a9-49f0-a17a-28b6efee918d)

![Screenshot_20231024-162451](https://github.com/KieronQuinn/Smartspacer/assets/5437803/7f71b5cf-2846-4c5a-8d2b-b492896e5228)

**Comment by KieronQuinn** [comment] 2023-10-24 22:36
Ok, my explanation was wrong, but the app is functioning as intended

The Installed tab is all plugins, prioritising those which have updates. 
The Available tab is just plugins which are not already installed. 

It was done this way so you can quickly see those which you haven't installed (the Available tab), and also see all of them including those already installed (the Installed tab)

**Comment by yochananmarqos** [comment] 2023-10-24 22:40
Sorry, that's not logical. Maybe label things a little more clearly as you're intending.

In my perspective, it's simple:

Installed means installed. Why would plugins that are not installed be there?

Available would mean plugins that are available which are not installed.

**Comment by KieronQuinn** [comment] 2023-10-24 23:06
The tab name could perhaps be clearer, maybe "All" would be better.

**Comment by yochananmarqos** [comment] 2023-10-24 23:10
No, really. How am I supposed to know which plugins I have installed if other plugins are listed in the installed section that are not installed? 

You're an awesome developer and I probably have used every app you've created over the years. I can't think of anything I've had an issue with with any other of your apps, so I'm sure you'll iron it all out.

However, I just don't understand why we aren't seeing this eye to eye....

**Comment by KieronQuinn** [comment] 2023-10-24 23:11
Fair point. I'll reopen.

**Comment by KieronQuinn** [comment] 2023-10-25 23:36
Fixed in 1.1.1

**Closed by KieronQuinn** 2023-10-25 23:36 UTC
Labels: bug

**Comment by yochananmarqos** [comment] 2023-10-25 23:53
Thanks! :tada:
