### ISSUE TITLE
[Bug] calendar target not working as described 

### ISSUE THREAD

**Issue by realmenwearpink2** [KieronQuinn/Smartspacer#80] opened 2023-12-11 17:41 UTC
### Description

I have the calendar target enabled, with many of my calendars toggled and settings to show 1hr before event and hide once event is done.

An even today did not trigger this behavior (event is currently happening and it is not showing up on smartspacer)

**Comment by KieronQuinn** [comment] 2023-12-11 17:46
I changed some of the logic in the latest version around events, which calendar app are you using and have you accepted the event (in Google Calendar this is by selecting "Yes" to going to the event)

**Comment by realmenwearpink2** [comment] 2023-12-11 19:45
I'm using Google calendar and yes the event has been accepted (I created it)
Now I'm seeing an event that I made show up using the calendar target.
Not sure why it wasn't showing up for the event before but is now

**Comment by KieronQuinn** [comment] 2023-12-11 19:56
Most likely just an upgrade issue that fixed itself then, closing.

**Closed by KieronQuinn** 2023-12-11 19:56 UTC
Labels: bug

**Comment by realmenwearpink2** [comment] 2023-12-12 21:30
The issue is still happening

**Comment by KieronQuinn** [comment] 2023-12-12 21:55
I can't reproduce it then. It's been showing multiple events all today for me (work ones) and I've just tested it and it's working fine for personal events too.

**Comment by realmenwearpink2** [comment] 2023-12-12 23:44
Hmmm is there a way I can send a bug report next time it happens?
Dump targets and actions?

**Comment by KieronQuinn** [comment] 2023-12-12 23:55
No because that only shows the actual targets. All I can suggest is seeing if you can find a pattern of the events that don't appear as I can't see one

**Comment by realmenwearpink2** [comment] 2023-12-13 16:14
After some basic testing, the only thing I can guess is that events created before installing Smartspacer are not showing up.
Does this make sense at all?
